### ISSUE TITLE
API endpoint URL

### ISSUE THREAD

**Issue by boverdui** [aridhia/fair-api-beta-utilities#10]
The API endpoint URL as copied from the FAIR UI using the 'Copy url to clipboard' functionality doesn't contain the https:// part at the start, but does have /api/ at the end. The scripts here do expect the former, but not the letter.  So either forementioned UI functionality or the scripts here have to be amended to bring both in line with each other.

**Comment by GlenQu** [comment]
I think it would be good to bring the documentation up to date, at least in the short term.  I will take an action to update.

**Comment by boverdui** [comment]
Do you mean as a workaround until either FAIR UI and/or scripts have been amended?

**Comment by martin-aridhia** [comment]
I think FAIR UI Copy to Clipboard should give you the full URL: https://<fair-domain>/api.
Checking with the devs why the https is omitted.

**Comment by GlenQu** [comment]
Sorry, yes scripts and README to be updated @boverdui.  Previously when I demoed this 'Copy URL' wasn't functionality and we just took the URL from the address bar, that is why '/api/' is in the example scripts.

**Comment by boverdui** [comment]
OK, if (1) the 'https:/'/ can be added to the Copy url to clipboard, (2) the '/api/' removed from the various scripts, and (3) the README updated accordingly, we should be fine.

**Comment by martin-aridhia** [comment]
FAIR UI will be updated to include the full API URL in the Copy to Clipboard:
https://<fair-domain>/api

**Comment by GlenQu** [comment]
Hi @boverdui, I have made the changes to accommodate the information we receive from the UI.  Could you give it a quick run through?
