### ISSUE TITLE
Error with select statement

### ISSUE THREAD

**Issue by xcountry02** [aridhia/fair-api-beta-utilities#8]
I have created a new API id for my database called sadd_tests_1, found here:
[https://fair.addi.ad-datainitiative.org/#/data/datasets/sadd_tests_1](https://fair.addi.ad-datainitiative.org/#/data/datasets/sadd_tests_1)

I also created new catalogue ids, like this one: Simul_ADNI_DB_1_subject

When I upload the file:
$ python ../fair-api-upload.py sadd_tests_1 data Simul_ADNI_DB_1_subject.csv
Dataset code: sadd_tests_1
File: Simul_ADNI_DB_1_subject.csv
Upload type: data
Destination: https://fair.addi.ad-datainitiative.org/api/files/datasets/sadd_tests_1/data
Uploading file ... Simul_ADNI_DB_1_subject.csv ...
Uploading file ... Simul_ADNI_DB_1_subject.csv ... Done

And when I run the following select:
$ python ../fair-api-select.py select-all.graphql

I am getting an error when I run it.  The select json, with the two outputs show the same error with different numbers, all of those are attached. 

A note on the attachments, it wouldn't let me attach them unless I changed the extension to txt.  So the select_json.txt is the select-all.graphql, the Simul_ADNI_DB_1_subject.xlsx is actually Simul_ADNI_DB_1_subject.csv (also Glen I have emailed him this one), but I can't attach csv, the other two are obvious, the errors I got yesterday and then today when rerunning it.

[select_ json.txt](https://github.com/aridhia/fair-api-beta-utilities/files/5262371/select_.json.txt)
[select_error_today.txt](https://github.com/aridhia/fair-api-beta-utilities/files/5262372/select_error_today.txt)
[select_error_yesterday.txt](https://github.com/aridhia/fair-api-beta-utilities/files/5262373/select_error_yesterday.txt)
[Simul_ADNI_DB_1_subject.xlsx](https://github.com/aridhia/fair-api-beta-utilities/files/5262474/Simul_ADNI_DB_1_subject.xlsx)

**Comment by RossBarnie** [comment]
I've tested this in a different environment successfully so I believe the errors above were due to temporary issues that have since been resolved. Please reopen this issue if you are still seeing those errors.
